// - Створити змінні. Присвоїти кожному з них значення: 'hello','owu','com', 'ua', 1, 10, -999, 123, 3.14, 2.7, 16, true, false.
//     Вивести кожну змінну за допомогою: console.log , alert, document.write
let wordOne = 'hello';
let wordTwo = 'owu';
let wordThree = 'com';
let wordFour = 'ua';
let numberOne = 1;
let numberTwo = 10;
let numberThree = -999;
let numberFour = 123;
let numberFive = 3.14;
let numberSix = 2.7;
let numberSeven = 16;
let xxx = true;
let yyy = false;
console.log(wordOne);
alert(wordOne);
document.write(wordOne);
console.log(wordTwo);
alert(wordTwo);
document.write(wordTwo);
console.log(wordThree);
alert(wordThree);
document.write(wordThree);
console.log(wordFour);
alert(wordFour);
document.write(wordFour);
console.log(numberOne);
alert(numberOne);
document.write(numberOne);
console.log(numberTwo);
alert(numberTwo);
document.write(numberTwo);
console.log(numberThree);
alert(numberThree);
document.write(numberThree);
console.log(numberFour);
alert(numberFour);
document.write(numberFour);
console.log(numberFive);
alert(numberFive);
document.write(numberFive);
console.log(numberSix);
alert(numberSix);
document.write(numberSix);
console.log(numberSeven);
alert(numberSeven);
document.write(numberSeven);
console.log(xxx );
alert(xxx);
document.write(xxx);
console.log(yyy);
alert(yyy);
document.write(yyy);
// - Переприсвоїти кожній змінній з завдання значення на довільне.
//     Вивести кожну змінну за допомогою: console.log , alert, document.write
wordOne = 'Hi';
wordTwo = 'I';
wordThree = 'am';
wordFour = 'Ruslana';
numberOne = 0;
numberTwo = 1;
numberThree = 2;
numberFour = 3;
numberFive = 4;
numberSix = 5;
numberSeven = 6;
xxx = false;
yyy = true;
console.log(wordOne);
alert(wordOne);
document.write(wordOne);
console.log(wordTwo);
alert(wordTwo);
document.write(wordTwo);
console.log(wordThree);
alert(wordThree);
document.write(wordThree);
console.log(wordFour);
alert(wordFour);
document.write(wordFour);
console.log(numberOne);
alert(numberOne);
document.write(numberOne);
console.log(numberTwo);
alert(numberTwo);
document.write(numberTwo);
console.log(numberThree);
alert(numberThree);
document.write(numberThree);
console.log(numberFour);
alert(numberFour);
document.write(numberFour);
console.log(numberFive);
alert(numberFive);
document.write(numberFive);
console.log(numberSix);
alert(numberSix);
document.write(numberSix);
console.log(numberSeven);
alert(numberSeven);
document.write(numberSeven);
console.log(xxx );
alert(xxx);
document.write(xxx);
console.log(yyy);
alert(yyy);
document.write(yyy);
// - Створити 3 змінних firstName, middleName, lastName, наповнити їх своїм ПІБ. З'єднати їх в одну змінну person. (Не об'єкт)
